version: '3.7'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: cafelove-backend
    container_name: backend_c
    command: npm run dev   # nodemon inside container
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo:27017/cafelove   # connection string
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: cafelove-frontend
    container_name: frontend_c
    command: npm run dev   # Vite dev server
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    container_name: mongo_c
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
  node_modules:
